Flask server
zawata/S19-Team2 pull request #15
Opened 2019-02-17 23:55 UTC by dlahtine

Contains the server portion.

To test:

1. `parcel build web/index.html` from root
2. `cmake --build build --target all` from root (may have to create build folder)
3. use python to run FlaskServer.py
4. In browser, open http://loaclhost:5000/web/index.html to view simulation
5. Download one of the test bsp files from google drive, and then visit http://loaclhost:5000/data.trajectory to upload it to the server.

You should get some debug messages, but no complaints (other than maybe a missing icon file)

2019-02-19 00:59 UTC, trevorforrey requested changes
It looks like this PR includes all the spyce build files. Would you be able to remove them from the PR?

2019-02-19 17:01 UTC, trevorforrey approved these changes

2019-02-19 17:02 UTC, trevorforrey commented
I was able to get it running when removing the sypce specific code. Host the page great, I just made some updates in the package.json and got it updated to merge!

2019-02-25 23:01 UTC, zawata approved these changes
I made a couple changes to the way the server handled files but nothing severe. 
Works amazingly for me. 

Approved

This should be merged so we can start work on a docker image.

2019-02-25 23:46 UTC, merged