T80 NAIF ID Conversion
zawata/S19-Team2 pull request #24
Opened 2019-03-02 02:34 UTC by zawata

One of the functions already existed but I've moved the declarations to make them more consistent.

to test:

from spyce import spyce 
spyce.id_to_str(399) # >earth
spyce.str_to_id("earth") # >399

2019-03-02 02:35 UTC, zawata commented
note: this doen't cover exception handling because it doesn't exist yet. the other 2 PRs should be merged in first, then I'll rebase this one.

2019-03-13 20:47 UTC, dlahtine requested changes
`spyce.str_to_id('MERCURY')
199
spyce.str_to_id('PLUTO')
999
spyce.str_to_id('PHOBOS')
401`

Tested both functions. Working as expected.

2019-03-13 21:23 UTC, dlahtine approved these changes

2019-03-14 02:46 UTC, zawata commented
updated to latest dev branch. doesn't change functionality.

2019-03-14 02:46 UTC, merged