T96 coverage windows2
zawata/S19-Team2 pull request #40
Opened 2019-03-26 00:07 UTC by dlahtine

Added an endpoint for fetching coverage windows.

To test: make an GET request to the /api/all_coverage_windows endpoint.

2019-03-27 06:58 UTC, zawata commented
remake this to not merge into master

2019-03-28 02:30 UTC, dlahtine commented
This is conflicting with other changes. needs refactoring.

2019-03-30 21:26 UTC, zawata requested changes
rebased on dev. logic is fine.

address the comments

2019-03-30 21:26 UTC, zawata commented on FlaskServer.py
> +    coverage_window['start'] = windows_piecewise[0][0]
you catch the internal error and pass which is fine, but then go on to operate on a potentially empty array. 
Passing 399 to the function throws an IndexError.
check `len(windows_piecewise) > 0`

2019-03-31 02:27 UTC, zawata approved these changes

2019-03-31 02:28 UTC, zawata commented
I fixed it. Merging

2019-03-31 02:28 UTC, merged